azs:
- cloud_properties:
    availability_zone: us-west-2a
  name: z1
- cloud_properties:
    availability_zone: us-west-2b
  name: z2
- cloud_properties:
    availability_zone: us-west-2c
  name: z3
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: large
  workers: 5
disk_types:
- cloud_properties:
    type: gp2
  disk_size: 3000
  name: default
- cloud_properties:
    type: gp2
  disk_size: 50000
  name: large
exodus:
  bosh: uswest2demo
  ca_cert: REDACTED
  dated: 2022-02-11 19:06:07 +0000
  deployer: cweibel
  features: ""
  is_director: false
  kit_is_dev: false
  kit_name: shield
  kit_version: 1.11.0
  pubkey: REDACTED
  url: https://10.4.1.9
  use_create_env: false
  vault_base: /secret/uswest2demo/shield
  version: 2.8.4
genesis:
  ci_mount: /secret/ci/
  env: uswest2demo
  exodus_mount: /secret/exodus/
  exodus_path: uswest2demo/shield
  min_version: 2.7.6
  secrets_mount: /secret/
  secrets_path: uswest2demo/shield
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - consumes:
      shield:
        from: shield
    name: shield-agent
    properties:
      core:
        ca: REDACTED
      env:
        http_proxy: ""
        https_proxy: ""
        no_proxy: ""
    release: shield
  - name: core
    properties:
      agent:
        key: REDACTED
      core:
        env: S.H.I.E.L.D.
      domain: 10.4.1.9
      require-shield-core: true
      tls:
        certificate: REDACTED
        key: REDACTED
      vault:
        tls:
          ca: REDACTED
          certificate: REDACTED
          key: REDACTED
    provides:
      shield:
        as: shield
        shared: true
    release: shield
  name: shield
  networks:
  - name: default
    static_ips:
    - 10.4.1.9
  persistent_disk_type: default
  stemcell: xenial
  vm_type: default
kit:
  features: []
  name: shield
  version: 1.11.0
meta:
  vault: /secret/uswest2demo/shield
name: uswest2demo-shield
networks:
- name: default
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0f56fcba8b1ba95b3
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.1.1
    range: 10.4.1.0/24
    reserved:
    - 10.4.1.0-10.4.1.5
    static:
    - 10.4.1.6-10.4.1.16
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-04066d0a30fd1c020
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.2.1
    range: 10.4.2.0/24
    reserved:
    - 10.4.2.0-10.4.2.5
    static:
    - 10.4.2.6-10.4.2.16
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0f2b10a0d103f3c83
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.3.1
    range: 10.4.3.0/24
    reserved:
    - 10.4.3.0-10.4.3.5
    static:
    - 10.4.3.6-10.4.3.16
  type: manual
- name: vip
  type: vip
params:
  external_domain: 10.4.1.9
  shield_disk_pool: default
  shield_network: default
  shield_static_ip: 10.4.1.9
  shield_vm_type: default
releases:
- name: shield
  sha1: e903af864cf0afdec83950431fcbd6b6a10395ee
  url: https://bosh.io/d/github.com/starkandwayne/shield-boshrelease?v=8.7.4
  version: 8.7.4
stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest
update:
  canaries: 0
  canary_watch_time: 1000-300000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-300000
vm_types:
- cloud_properties:
    ephemeral_disk:
      size: 3000
      type: gp2
    instance_type: t2.micro
  name: default
- cloud_properties:
    ephemeral_disk:
      size: 30000
      type: gp2
    instance_type: m4.large
  name: large