pipeline:
  name: shield-platform-pipeline
  git:
    owner: starkandwayne
    repo:  demo-shield-deployments
    branch: master
    private_key: (( vault "concourse/demo/shield/github:private_key" ))

  vault:
    url:    https://10.4.1.7
    verify: no

  slack:
    channel: '#botspam'
    webhook: (( vault "concourse/genesis/slack:webhook" ))

  boshes:
    dev:
      alias:    dev
      url:      https://10.4.16.4:25555
      ca_cert:  (( vault "secret/dev/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/dev/bosh/users/admin:password" ))
    test:
      alias:    uswest2demo
      url:      https://10.4.1.4:25555
      ca_cert:  (( vault "secret/uswest2demo/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/uswest2demo/bosh/users/admin:password" ))

  layouts:
    default: |+
      auto *dev
      dev -> uswest2demo

  groups:
    default:
    - dev
    - uswest2demo
